#!/bin/bash

# helper script to set up the remote and deploy hook
# usage: setup-repo [deploy url]
# execute from the root of repository

TARGET_FILE=$0
cd `dirname $TARGET_FILE`
TARGET_FILE=`basename $TARGET_FILE`

# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done

# Compute the canonicalized name by finding the physical path
# for the directory we're in and appending the target file.
PHYS_DIR=`pwd -P`
SRC="$(dirname "$PHYS_DIR/$TARGET_FILE")/src"
GIT_DIR="$(git rev-parse --git-dir)"

NAME="deploy"
URL="$1"
if [ -z "$URL" ]; then
    echo "Specify remote url for deploy, e.g."
    echo "  foo@myserver:/usr/local/myproject"
    read -p "Remote: " URL
    [ -n "$URL" ] || exit
    echo
    echo "$URL needs to be a Git repository with a work tree."
    echo "If you haven't created it already, you can do that now."
    echo
    read -p "Press Enter to continue"
    echo
fi

"$SRC/setup-remote" "$NAME" "$URL"
echo
echo -e "\x1b[32\x6dAll set up!\x1b[0\x6d Try it:"
echo "  git push $NAME"
