#!/bin/bash

cd $GIT_DIR/..
unset GIT_DIR GIT_WORK_TREE

while read OLD NEW REF; do
  [ $REF != refs/heads/deploy ] && continue
  [ $NEW == 0000000000000000000000000000000000000000 ] && continue
  echo -e '\x1b[33;1mAuto-deploying on' $(hostname) '\x1b[0m' >&2
  # build new tree
  git read-tree -m --aggressive "$NEW:" || exit
  git checkout-index -a -f || exit
  git commit --allow-empty --untracked-files=no \
             -m "Deployed commit $(git rev-parse --short $NEW)" || exit
  # run any post-deploy scripts found in deploy/
  if [ -d "deploy" ]; then
    echo -e '\x1b[33;1mRunning post-deploy scripts\x1b[0m' >&2
    find deploy -type f -perm +0111 -exec {} \;
  fi
done
